server:
  port: 8081
  application:
    name: spring-boot-base-demo





spring:
  profiles:
#    active: @env@
    active: sit
  http:
    encoding:
      charset: utf-8
      enabled: true

#监听器，监听事件
#context:
#  listener:
#    classes: com.ffan.demo.listener.MyApplicationListener

service:
  hello:
    name: tree