server:
  port: 10001
  application:
    name: spring-boot-sharding-jdbc


mybatis:
  mapperLocations: classpath:config/mybatis/springboot/shardingjdbc/*.xml
  typeAliasesPackage: com.ejyi.demo.springboot.shardingjdbc.po

#spring:
#  datasource:
#    name: ejyi
#    url: jdbc:mysql://127.0.0.1:3306/demo0?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
#    username: root
#    password: mysqlpw
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: config,log4j,stat
#    maxActive: 30
#    initialSize: 2
#    maxWait: 60000
#    minIdle: 2
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20


sharding:
  jdbc:
    datasource:
      names: ds_0,ds_1
      ds_0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/demo0
        username: root
        password: mysqlpw
        filters: config,log4j,stat
        maxActive: 30
        initialSize: 2
        maxWait: 60000
        minIdle: 2
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      ds_1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/demo1
        username: root
        password: mysqlpw
        filters: config,log4j,stat
        maxActive: 30
        initialSize: 2
        maxWait: 60000
        minIdle: 2
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    config:
      sharding:
        default-data-source-name: ds_0
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds_${user_id % 2}
        tables:
          t_user:
            actual-data-nodes: ds_0.t_user_${0..1}
            table-strategy:
              inline:
                sharding-column: user_id
                algorithm-expression: t_user_${user_id % 2}
            key-generator-column-name: user_id
          t_order:
            actual-data-nodes: ds_${0..1}.t_order_${0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_${order_id % 2}
            key-generator-column-name: order_id