spring:
  application:
    name: activiti-01
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.170.17:3306/zkdash?useUnicode=true&characterEncoding=UTF-8&useSSL=false&transformedBitIsBoolean=true&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
      username: root
      password: test
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 15
      pool-name: activiti-01-db
  activiti:
    database-schema-update: true
    check-process-definitions: false

logging:
  path: ./logs
  register-shutdown-hook: false